# Generated by Django 4.0.3 on 2022-03-23 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Wilaya')),
                ('relai_delivery', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Livraison point de Relais')),
                ('home_delivery', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Livraison à domicile')),
                ('active', models.BooleanField(default=True, verbose_name='Livraison Active')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de dernière mise à jour')),
            ],
            options={
                'verbose_name': 'Wilaya',
                'verbose_name_plural': '1. Wilayas',
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Commune')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de dernière mise à jour')),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.wilaya', verbose_name='Wilaya')),
            ],
            options={
                'verbose_name': 'Commune',
                'verbose_name_plural': '2. Communes',
            },
        ),
    ]
