# Generated by Django 4.0.3 on 2022-03-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_warehouse_manager'),
        ('accounts', '0002_user_warehouse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('is_manager', 'warehouse')},
        ),
    ]
