# Generated by Django 4.0.3 on 2022-03-16 13:55

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='ordre')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/categories')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categorys',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('upc', models.CharField(max_length=200, verbose_name='code article')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL')),
                ('reference', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Référence / code a bar')),
                ('text', models.TextField(blank=True, null=True, verbose_name='petit text')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Ancien prix')),
                ('buy_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name="prix d'achat")),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
                ('new', models.BooleanField(default=False, verbose_name='Nouveau')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de dernière mise à jour')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_products', to='inventory.brand')),
                ('category', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='WareHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du revendeur/point de stockage')),
                ('address', models.CharField(max_length=200, verbose_name='address')),
            ],
            options={
                'verbose_name': 'WareHouse',
                'verbose_name_plural': 'WareHouses',
            },
        ),
        migrations.CreateModel(
            name='WareHouseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='inventory.warehouse')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='inventory.product')),
            ],
            options={
                'verbose_name': 'WareHouseItem',
                'verbose_name_plural': 'WareHouseItems',
            },
        ),
    ]
