# Generated by Django 4.0.3 on 2022-03-20 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouseitem',
            old_name='quantite',
            new_name='quantity',
        ),
    ]
