# Generated by Django 4.0.3 on 2022-03-21 14:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0003_warehouse_created_warehouse_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='manager',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='manager'),
        ),
    ]
