# Generated by Django 4.0.3 on 2022-03-21 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_warehouse_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='manager',
        ),
    ]
