# Generated by Django 4.0.3 on 2022-03-16 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom du fournisseur')),
                ('adress', models.CharField(blank=True, max_length=150, null=True, verbose_name='Adresse du fournisseur')),
                ('rc_code', models.CharField(blank=True, max_length=150, null=True, verbose_name='numéro du registre de commerce')),
                ('art_code', models.CharField(blank=True, max_length=150, null=True, verbose_name="numéro d'article")),
                ('nif_code', models.CharField(blank=True, max_length=150, null=True, verbose_name='numéro identité fiscale')),
            ],
            options={
                'verbose_name': 'supplier',
                'verbose_name_plural': 'suppliers',
            },
        ),
        migrations.CreateModel(
            name='WareHouseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(blank=True, choices=[('BC', 'Bon de commande'), ('FF', 'Facture finale'), ('BL', 'Bon de livraison')], max_length=2, null=True, verbose_name='type de commande')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('is_return', models.BooleanField(default=False)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='remise')),
                ('delivery_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='cout de livraison')),
                ('note', models.TextField(blank=True, null=True)),
                ('delivery_man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_orders', to=settings.AUTH_USER_MODEL, verbose_name='livreur')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_orders', to=settings.AUTH_USER_MODEL, verbose_name='receiver')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_orders', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
            ],
            options={
                'verbose_name': 'WareHouseOrder',
                'verbose_name_plural': 'WareHouseOrders',
            },
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Wilaya')),
                ('relai_delivery', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Livraison point de Relais')),
                ('home_delivery', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Livraison à domicile')),
                ('active', models.BooleanField(default=True, verbose_name='Livraison Active')),
            ],
            options={
                'verbose_name': 'Wilaya',
                'verbose_name_plural': '1. Wilayas',
            },
        ),
        migrations.CreateModel(
            name='WareHouseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantité')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='prix')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.warehouseorder', verbose_name='commande')),
                ('warehouse_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_order_items', to='inventory.warehouseitem', verbose_name='produit')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantité')),
                ('is_received', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='prix')),
                ('note', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_orders', to='order.warehouseorder', verbose_name='commande')),
                ('warehouse_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_order_items', to='inventory.warehouseitem', verbose_name='produit')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_type', models.CharField(blank=True, choices=[('BC', 'Bon de commande'), ('BR', 'Bon de récéption')], max_length=2, null=True, verbose_name='type de commande')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_received', models.BooleanField(default=False)),
                ('is_return', models.BooleanField(default=False)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='remise')),
                ('delivery_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='cout de livraison')),
                ('note', models.TextField(blank=True, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_orders', to=settings.AUTH_USER_MODEL, verbose_name='receiver')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_orders', to='order.supplier', verbose_name='sender')),
            ],
            options={
                'verbose_name': 'supply_order',
                'verbose_name_plural': 'supply_orders',
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Commune')),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.wilaya', verbose_name='Wilaya')),
            ],
            options={
                'verbose_name': 'Commune',
                'verbose_name_plural': '2. Communes',
            },
        ),
        migrations.CreateModel(
            name='ClientOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantité')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='prix')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_orders', to='order.warehouseorder', verbose_name='commande')),
                ('warehouse_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_order_items', to='inventory.warehouseitem', verbose_name='produit')),
            ],
        ),
        migrations.CreateModel(
            name='ClientOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Prenom')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Adresse')),
                ('phone', models.CharField(max_length=25, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('order_type', models.CharField(blank=True, choices=[('BC', 'Bon de commande'), ('FF', 'Facture finale'), ('BL', 'Bon de livraison')], max_length=2, null=True, verbose_name='type de commande')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('is_cib', models.BooleanField(default=False)),
                ('cib_order_code', models.CharField(blank=True, max_length=2, null=True, verbose_name='code de commande cib')),
                ('coupon', models.CharField(blank=True, max_length=2, null=True, verbose_name='coupon')),
                ('is_return', models.BooleanField(default=False)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='remise')),
                ('delivery_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='cout de livraison')),
                ('note', models.TextField(blank=True, null=True)),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.commune')),
                ('delivery_man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_orders', to=settings.AUTH_USER_MODEL, verbose_name='livreur')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_client_orders', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
            ],
            options={
                'verbose_name': 'ClientOrder',
                'verbose_name_plural': 'ClientOrders',
            },
        ),
    ]
