# Generated by Django 4.0.3 on 2022-03-20 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_quantite_warehouseitem_quantity'),
        ('order', '0002_clientorder_created_clientorder_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_orders', to='order.clientorder', verbose_name='commande'),
        ),
        migrations.AlterField(
            model_name='supplyorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_order_items', to='order.supplyorder', verbose_name='commande'),
        ),
        migrations.AlterField(
            model_name='supplyorderitem',
            name='warehouse_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouseitem', verbose_name='produit'),
        ),
    ]
