# Generated by Django 4.0.3 on 2022-03-21 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_clientorder_delivery_man'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientorder',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='warehouseorder',
            name='sender',
        ),
    ]
