# Generated by Django 4.0.3 on 2022-03-23 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('order', '0005_remove_clientorder_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorder',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.commune'),
        ),
        migrations.DeleteModel(
            name='Commune',
        ),
        migrations.DeleteModel(
            name='Wilaya',
        ),
    ]
