# Generated by Django 4.0.3 on 2022-03-23 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0006_alter_clientorder_commune_delete_commune_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseorder',
            name='delivery_man',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_orders', to=settings.AUTH_USER_MODEL, verbose_name='livreur'),
        ),
    ]
