# Generated by Django 4.0.3 on 2022-03-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_warehouseorder_delivery_man'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplyorderitem',
            name='is_received',
        ),
        migrations.AddField(
            model_name='warehouseorder',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='numéro'),
        ),
    ]
